Extend edit profile with paas mutation
gctools-outilsgc/gcconnex pull request #2304
Opened 2020-08-31 14:08 UTC by ethanWallace

Extends the edit profile action with the graphql mutation to paas. If graphql mutation fails, the edit profile action will be canceled.

2020-08-31 18:34 UTC, nschonni commented on Dockerfile
> +RUN mkdir /app && mkdir /app/pleio && mkdir /app/paas_integration && curl -sS https://getcomposer.org/installer | php5 -- --install-dir=/usr/local/bin --filename=composer
```suggestion
RUN mkdir /app && \
        mkdir /app/pleio && \
        mkdir /app/paas_integration && \
        curl -sS https://getcomposer.org/installer | php5 -- --install-dir=/usr/local/bin --filename=composer
```

2020-09-15 15:20 UTC, piet0024 requested changes

2020-09-15 15:20 UTC, piet0024 commented on mod/paas_integration/start.php
> +            'address' => array(
If the address field is left empty, the profile service throws back  something along the lines of `400 Bad Request ... got invalid value`. However the other fields can be empty and everything fires properly.

2020-09-15 19:53 UTC, piet0024 approved these changes

2020-09-16 14:07 UTC, merged