Career application deadline
gctools-outilsgc/gcconnex pull request #2563
Opened 2023-06-21 15:54 UTC by AdiMakkar

Application Deadline requirement for the Career Marketplace is removed.

2023-06-21 15:55 UTC, AdiMakkar commented
Testing requirements incoming.

2023-06-22 15:51 UTC, Phanoix requested changes

2023-06-22 15:51 UTC, Phanoix commented on mod/missions/lib/missions-errors.php
> + 	//$date_dead = strtotime($input_array['deadline']); Adi - The requirement to check for the Application Deadline on page 2
You still want to keep this part, it's needed for the error checking below.

2023-06-22 16:24 UTC, AdiMakkar commented
Fixes #2559. Additionally removes the "required" keyword from the edit form for opportunity and based on testing, adds the "required" keyword to the page 2 of the form since 'Type Of Opportunity' is a required condition.

2023-06-22 17:15 UTC, Phanoix approved these changes

2023-06-22 19:51 UTC, buryva approved these changes

2023-06-26 17:48 UTC, merged